// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzkE-w0kZuPhjVTnHFxvIVUCKPZnij7iA',
    appId: '1:721396144922:web:989dcab16004e4bcceaaa3',
    messagingSenderId: '721396144922',
    projectId: 'practice-e0836',
    authDomain: 'practice-e0836.firebaseapp.com',
    storageBucket: 'practice-e0836.appspot.com',
    measurementId: 'G-6GCM5BF23E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1pcL75u4qe6hCb8f4X_KQwRr2Yw80Q0',
    appId: '1:721396144922:android:9de1744544bac211ceaaa3',
    messagingSenderId: '721396144922',
    projectId: 'practice-e0836',
    storageBucket: 'practice-e0836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkUsg5KtbolE0ETy771jvj9drorg8LSfw',
    appId: '1:721396144922:ios:829736e1445ae9a6ceaaa3',
    messagingSenderId: '721396144922',
    projectId: 'practice-e0836',
    storageBucket: 'practice-e0836.appspot.com',
    iosBundleId: 'com.example.firestore',
  );
}
